version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ConnectionString=mongodb://mongo:27017/poll
      - PORT=8000
      - SECRET_KEY=ak47
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 
